version: "3"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: "8080"
      DATABASE_CONNECTION_STRING: "jdbc:postgresql://db/mobile_developer_course"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    depends_on:
      - db
    networks:
      - db_network
    restart: always

  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "mobile_developer_course"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - db_network
    restart: always

networks:
  db_network:
    driver: bridge